version: "3"

services:
  front:
    build:
      context: .
      args:
        BASE_IMAGE_ENVIRONMENT: 'develop'
    environment:
      NODE_ENV: develop
    ports:
      - "3000:3000"
    volumes:
      - doorvel:/app
      - /app/node_modules
    env_file:
      - ../.env

volumes:
  doorvel:
    driver_opts:
      type: none
      device: $PWD
      o: bind